vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    station:
      uri_prefix: /images/station
      upload_destination: "%kernel.project_dir%/public/images/station"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
